directory: /data/music
library: /data/beets/library.db

# Load plugins beets can use.
plugins:
- beetstream
- web
- webm3u
- webrouter

# Run a web server that serves a GUI, Subsonic API and M3U playlists.
# See https://github.com/mgoltzsche/beets-webrouter
webrouter:
  host: 0.0.0.0
  port: 8337
  routes:
    /:
      plugin: web
    /favicon.ico:
      plugin: webrouter.favicon
    /subsonic:
      plugin: beetstream
      config:
        never_transcode: true
        playlist_dir: /data/playlists
    /m3u:
      plugin: webm3u

# Run a subsonic server.
# See https://github.com/BinaryBrain/Beetstream
beetstream:
  host: 0.0.0.0
  port: 8080
  never_transcode: true

# Run a web server that provides a simple GUI and API.
# See https://beets.readthedocs.io/en/stable/plugins/web.html
web:
  host: 0.0.0.0
  port: 8337
  reverse_proxy: true
  readonly: true

# Run a web server to serve the playlists.
# See https://github.com/mgoltzsche/beets-webm3u
webm3u:
  host: 0.0.0.0
  port: 8339
  playlist_dir: /data/playlists
