directory: /data/music
library: /data/beets/library.db

paths:
  default: Albums/%title{$albumartist}/$album%aunique{}/$track $title
  singleton: Singles/%title{$first_artist}/$title
  comp: Compilations/$album%aunique{}/$track $title

# Load plugins beets can use.
plugins:
- web

# Run a web server that provides a simple GUI and API.
# See https://beets.readthedocs.io/en/stable/plugins/web.html
web:
  host: 127.0.0.1
  port: 8336 # 8337 is served by reverse-proxy to provide range query support.
  reverse_proxy: true
  readonly: true
