# kpt setter values that are applied to other KRM yaml files by `kpt fn render`.
# See also: https://kpt.dev/guides/variant-constructor-pattern
apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /app-config
  name: app-config
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|app-config'
data:
  version: "0.13.0"
  name: beets
  title: Beets
  image: ghcr.io/mgoltzsche/beets
  plugins-image: ghcr.io/mgoltzsche/beets-plugins
  port: 8337
  healthcheck: /
