apiVersion: skaffold/v3alpha1
kind: Config
metadata: # kpt-merge: /data
  name: data
  annotations:
    internal.kpt.dev/upstream-identifier: 'skaffold|Config|default|data'
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: ghcr.io/mgoltzsche/beets
    docker:
      dockerfile: Dockerfile
  - image: ghcr.io/mgoltzsche/beetstream # kpt-set: ${image}
    docker:
      dockerfile: Dockerfile-beetstream
    requires:
    - image: ghcr.io/mgoltzsche/beets
      alias: BASEIMAGE
  - image: ghcr.io/mgoltzsche/beets-plugins # kpt-set: ${plugins-image}
    docker:
      dockerfile: Dockerfile-plugins
    requires:
    - image: ghcr.io/mgoltzsche/beetstream # kpt-set: ${image}
      alias: BASEIMAGE
  local:
    push: false
manifests:
  kustomize:
    paths:
    - ./deploy/default
profiles:
- name: release
  build:
    platforms:
    - linux/arm64/v8
    - linux/amd64
    local:
      push: true
      useBuildkit: true
