apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: beets # kpt-set: ${name}
resources:
- serviceaccount.yaml
- service.yaml
- deployment.yaml
- ingress.yaml
