apiVersion: v1
kind: PersistentVolumeClaim
metadata: # kpt-merge: /beets-data
  name: beets-data
  annotations:
    internal.kpt.dev/upstream-identifier: '|PersistentVolumeClaim|default|beets-data'
spec:
  accessModes:
    - ReadWriteOnce
  #storageClassName: local-path
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
